[settings]
adminGroup = "sudo"
defaultMins = 10

[messages]
error = "An internal error occurred."
help = """StaffToggle help:
- /staff on (time)
- /staff off"""
noPerm = "You do not have permission to run this!"
notPlayer = "Only players can run this command."
